[common]
user = ja9ldmtrsivnycok

sakura_mode = true
login_fail_exit = false

server_addr = frp-fit.com
server_port = 8088

[Arknights_Voice]
# id = 27615205
type = tcp
local_ip = 127.0.0.1
local_port = 5173
remote_port = 21605
